/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        brand: {
          50: "#eef2ff",
          500: "#6366f1",
          600: "#4f46e5",
          700: "#4338ca",
        },
        surface: "#faf8ff",
        outline: "#906f6b",
        "surface-container": "#eaedff",
        "tertiary-fixed": "#9bf0ff",
        "surface-variant": "#dae2fd",
        "tertiary-fixed-dim": "#68d6e8",
        "surface-container-highest": "#dae2fd",
        "on-tertiary-container": "#f7feff",
        "on-surface": "#131b2e",
        "on-primary-container": "#fffbff",
        "secondary-fixed": "#d8e2ff",
        "outline-variant": "#e5bdb8",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "surface-bright": "#faf8ff",
        "secondary-container": "#2170e4",
        "tertiary-container": "#00818f",
        "primary-fixed": "#ffdad6",
        tertiary: "#006672",
        "surface-container-high": "#e2e7ff",
        "on-secondary-container": "#fefcff",
        "surface-tint": "#bd1016",
        error: "#ba1a1a",
        "surface-container-low": "#f2f3ff",
        primary: "#b90b14",
        "inverse-on-surface": "#eef0ff",
        "on-secondary-fixed-variant": "#004395",
        "surface-dim": "#d2d9f4",
        "primary-fixed-dim": "#ffb4ab",
        secondary: "#0058be",
        "on-secondary-fixed": "#001a42",
        "on-surface-variant": "#5c403c",
        "on-primary-fixed": "#410002",
        "on-primary-fixed-variant": "#93000a",
        "on-tertiary-fixed": "#001f24",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "inverse-primary": "#ffb4ab",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#004f58",
        "inverse-surface": "#283044",
        "on-background": "#131b2e",
        "primary-container": "#de2e2a",
        background: "#faf8ff",
        "secondary-fixed-dim": "#adc6ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "card-gap": "20px",
        gutter: "24px",
        unit: "8px",
        "section-margin": "48px",
        "container-padding": "32px",
      },
      fontFamily: {
        "label-caps": ["Inter", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        display: ["Space Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "0em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
